DELETE http://localhost:3001/api/persons/62de6b9a5082a356c5393e70

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{
	"name": "jiof wefef",
	"number" : "123-1233332"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{
	"name": "" ,
	"number" : "123-1233332"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{
	"name": "Arto Hellas" ,
	"number" : "123-1233332"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{
	"name": "Arto Hellas" ,
	"number" : "999-999999"
}