DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{
	"name": "jiof wefef",
	"number" : "123-1233332"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{
	"name": "" ,
	"number" : "123-1233332"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{
	"name": "Arto Hellas" ,
	"number" : "123-1233332"
}